name       : gnome-multi-writer
version    : 3.35.90
release    : 16
source     :
    - https://download.gnome.org/sources/gnome-multi-writer/3.35/gnome-multi-writer-3.35.90.tar.xz : b7fe3667e23402ee1d5b01c5d271dd6475a79e4a70843f0e3c97f5dca4fc6f1f
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Gnome Multi-USB Writer
description: |
    Gnome Multi-USB Writer
builddeps  :
    - pkgconfig(gusb)
    - pkgconfig(gudev-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libusb-1.0)
    - pkgconfig(polkit-gobject-1)
    - pkgconfig(udisks2)
    - itstool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
