name       : gnome-multi-writer
version    : 3.32.0
release    : 9
source     :
    - https://download.gnome.org/sources/gnome-multi-writer/3.32/gnome-multi-writer-3.32.0.tar.xz : 098c1586962698c86e586925d9ea52262eaa17dbe2bab74230f2dff8a45ad0cb
license    : GPL-2.0
component  : desktop.gnome
summary    : Gnome Multi-USB Writer
description: |
    Gnome Multi-USB Writer
builddeps  :
    - pkgconfig(gusb)
    - pkgconfig(gudev-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libusb-1.0)
    - pkgconfig(polkit-gobject-1)
    - pkgconfig(udisks2)
    - itstool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
