name       : gnome-multi-writer
version    : 3.28.0
release    : 8
source     :
    - https://download.gnome.org/sources/gnome-multi-writer/3.28/gnome-multi-writer-3.28.0.tar.xz : 5de6cb0779209449b598b7597cf1f60c6cf902a32b3b115299848f02beeddb1a
license    : GPL-2.0
component  : desktop.gnome
summary    : Gnome Multi-USB Writer
description: |
    Gnome Multi-USB Writer
builddeps  :
    - pkgconfig(gusb)
    - pkgconfig(gudev-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libusb-1.0)
    - pkgconfig(polkit-gobject-1)
    - pkgconfig(udisks2)
    - itstool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
