name       : gnome-multi-writer
version    : 3.22.1
release    : 5
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-multi-writer/3.22/gnome-multi-writer-3.22.1.tar.xz : 02fe592b9c6c3b1b76dc7436f10a60673b8e89fb0f81f8e99ae943f6ba139fb6
license    : GPL-2.0
component  : desktop.gnome
summary    : Gnome Multi-USB Writer
description: |
    Gnome Multi-USB Writer
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(gusb)
    - pkgconfig(udisks2)
    - pkgconfig(gudev-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libusb-1.0)
    - itstool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
