name       : gnome-multi-writer
version    : 3.18.0
release    : 3
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-multi-writer/3.18/gnome-multi-writer-3.18.0.tar.xz : 4887d1edb64a242337628d98446ab8128deea5e83211147667f77d388dc8f30f
license    : GPL-2.0
summary    : Gnome Multi-USB Writer
description: |
    Gnome Multi-USB Writer
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(gusb)
    - pkgconfig(udisks2)
    - pkgconfig(gudev-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libusb-1.0)
    - itstool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
