name       : gnome-multi-writer
version    : 3.20.0
release    : 4
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-multi-writer/3.20/gnome-multi-writer-3.20.0.tar.xz : 85f723cd935850e8e0b8f04669f0ab39838e447e4fb31d64107be4a30426ddf6
license    : GPL-2.0
summary    : Gnome Multi-USB Writer
description: |
    Gnome Multi-USB Writer
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(gusb)
    - pkgconfig(udisks2)
    - pkgconfig(gudev-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libusb-1.0)
    - itstool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
